In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
# from __future__ import print_function   # not required in py3
import torch
print(torch.__version__)

1.3.1


<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



#### Uninitialized tensor
Construct a 5x3 matrix, uninitialized:

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


#### Tensor of random numbers
Construct a randomly initialized matrix:

In [12]:
torch.random.manual_seed(4242)
x = torch.rand(5, 3)
print(x)

tensor([[0.1871, 0.9937, 0.7461],
        [0.7066, 0.9860, 0.9178],
        [0.3464, 0.4530, 0.1415],
        [0.2940, 0.2574, 0.4902],
        [0.5460, 0.6324, 0.8209]])


#### Tensor of zeros
Construct a matrix filled zeros and of dtype long:

In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### Tensor from data
Construct a tensor directly from data:

In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


#### Tensor from an existing tensor
or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user.  In the first example, an existing
tensor's method is used, whereas in the second, a torch function is used.

In [15]:
# new_ones() creates a new tensor on the same device and having the same data type as x, unless overridden
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1305, -3.3220, -0.6998],
        [-1.9594, -0.1713, -0.2406],
        [ 0.1050,  1.8135,  1.3169],
        [-1.4447, -0.9711,  1.5092],
        [ 1.3756, -0.9184, -0.0606]])


Get its size:



In [22]:
print(x.size())
print('Is torch.Size a tuple:', isinstance(x.size(), tuple))

torch.Size([5, 3])
Is torch.Size a tuple: True


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

#### Addition: syntax 1 using operator `+`

In [23]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1800e+00, -3.1077e+00, -2.0055e-01],
        [-9.8913e-01, -8.0077e-02,  6.9322e-02],
        [ 3.2824e-01,  1.8238e+00,  2.1289e+00],
        [-1.1465e+00,  1.3989e-03,  1.7308e+00],
        [ 1.4531e+00, -5.5350e-01,  5.6487e-01]])


#### Addition: syntax 2 using function `torch.add()`

In [24]:
print(torch.add(x, y))

tensor([[ 1.1800e+00, -3.1077e+00, -2.0055e-01],
        [-9.8913e-01, -8.0077e-02,  6.9322e-02],
        [ 3.2824e-01,  1.8238e+00,  2.1289e+00],
        [-1.1465e+00,  1.3989e-03,  1.7308e+00],
        [ 1.4531e+00, -5.5350e-01,  5.6487e-01]])


#### Addition: providing an output tensor as argument using function `torch.add()`

In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1800e+00, -3.1077e+00, -2.0055e-01],
        [-9.8913e-01, -8.0077e-02,  6.9322e-02],
        [ 3.2824e-01,  1.8238e+00,  2.1289e+00],
        [-1.1465e+00,  1.3989e-03,  1.7308e+00],
        [ 1.4531e+00, -5.5350e-01,  5.6487e-01]])


#### Addition: in-place using instance method `add_()`



In [26]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1800e+00, -3.1077e+00, -2.0055e-01],
        [-9.8913e-01, -8.0077e-02,  6.9322e-02],
        [ 3.2824e-01,  1.8238e+00,  2.1289e+00],
        [-1.1465e+00,  1.3989e-03,  1.7308e+00],
        [ 1.4531e+00, -5.5350e-01,  5.6487e-01]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

#### Indexing
You can use standard NumPy-like indexing with all bells and whistles!

In [28]:
# print the second column
print(x[:, 1])

tensor([-3.3220, -0.1713,  1.8135, -0.9711, -0.9184])


#### Resizing with `torch.view`
If you want to resize/reshape tensor, you can use ``torch.view``:

In [35]:
x = torch.randn(4, 4)
print('x.size', x.size())
y1 = x.view(16)
print('y.size', y1.size())
# A y2 is different--it's a 1 x 1 x 16 tensor
y2 = x.view(1, 1, 16)
print('y.size', y2.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print('z.size', z.size())
# only one dimension may be inferred

x.size torch.Size([4, 4])
y.size torch.Size([16])
y.size torch.Size([1, 1, 16])
z.size torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [37]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9528])
0.9527547359466553


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  [here](https://pytorch.org/docs/torch>).


NumPy Bridge--Converting to and from numpy
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

### Converting a Torch Tensor to a NumPy Array

In [38]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


The numpy array is a reference.  So any changes to `a` also changes `b`.

In [41]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### Converting NumPy Array to Torch Tensor
Torch tensor is a reference to the numpy array.  Any changes to the latter also changes the former.

In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [46]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('Sorry, CUDA is not available')

Sorry, CUDA is not available
